export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//lists
export const LOAD_LISTS_SUCCESS = 'LOAD_LISTS_SUCCESS';
export const BROWSE_LISTS = 'BROWSE_LISTS';
export const SAVE_LIST_SUCCESS = 'SAVE_LIST_SUCCESS';
export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS';
export const SAVE_LIST = 'SAVE_LIST'; //do we need this

//student' lists
export const SIGNUP_STUDENT_TO_LIST_SUCCESS = 'SIGNUP_STUDENT_TO_LIST_SUCCESS';
export const LOAD_STUDENT_LISTS_SUCCESS = 'LOAD_STUDENT_LISTS_SUCCESS';

//learnItem
export const SAVE_LEARNITEM_SUCCESS = 'SAVE_LEARNITEM_SUCCESS';
export const SAVE_LEARNITEM = 'SAVE_LEARNITEM';
export const LOAD_LEARNITEMS_SUCCESS = 'LOAD_LEARNITEMS_SUCCESS';
export const CHANGE_LEARNITEMPAGE = 'CHANGE_LEARNITEMPAGE';

export const LOAD_LEARNABLE_LEARNITEMS_SUCCESS = 'LOAD_LEARNABLE_LEARNITEMS_SUCCESS';

//login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

//signup
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';