export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_LISTS_SUCCESS = 'LOAD_LISTS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const BROWSE_LISTS = 'BROWSE_LISTS'
export const SAVE_LIST_SUCCESS = 'SAVE_LIST_SUCCESS';
export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS';
export const SAVE_LIST = 'SAVE_LIST'; //do we need this

//learnitem

export const LOAD_LEARNITEMS_SUCCESS = 'LOAD_LEARNITEMS_SUCCESS'